### ISSUE TITLE
add some kind of save/like button

### ISSUE THREAD

**Issue by KraXen72** [probablykasper/kadium#9]
it would be nice if i could save certain videos when i've watched them and deemed them to be good enough to be rewatched. I know this can be done by simply adding them to a playlist on youtube.com but it would be nice in app. I understand if out of scope tho.

**Comment by probablykasper** [comment]
Yeah I'm not really too sure about the benefit of saving videos to Kadium instead of using playlists. It definitely wouldn't be much of a problem to at least have it in the `File` menu though.

I'd be happy to accept PRs for the feature requests (or go for them myself if someone decides to become a GitHub sponsor)
